"""Golden-set verification worksheet (prep task P2, spec §8).

Spec §8 and P2 are explicit: "every expected clause is human-verified before
commit" / "no unverified case enters the JSONL". The suites in ``evals/suites/``
are still marked ``## DRAFT`` and carry ``VERIFY:`` flags — their
``expected_clauses`` were drafted, not confirmed against the ingested text.

This script does the MECHANICAL half of that verification so the human only has
to review the exceptions. For every case it asks two questions against the
corpus that is actually in the database:

  1. EXISTS   — does the expected clause exist as an ingested Section at all?
                (A case expecting a clause we never ingested can never pass, and
                would silently depress recall forever.)
  2. SUPPORTS — does that clause's own text contain the case's expected_facts?
                Matching is deliberately crude (normalized token overlap): it is
                a TRIAGE signal, not a judgement. A low score means "a human
                should look at this", never "this case is wrong".

It NEVER writes to evals/suites/ (CLAUDE.md rule 13 — that directory is
human-owned). Output is a markdown worksheet; applying its findings is the
owner's call and the owner's sign-off.

Usage (from core/):
    uv run python ../scripts/verify_golden_set.py --slug far-25
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import psycopg

_REPO_ROOT = Path(__file__).resolve().parent.parent
_SUITES_DIR = _REPO_ROOT / "evals" / "suites"
_OUT = _REPO_ROOT / "evals" / "reports" / "golden-set-verification.md"

# Words too common to carry evidence — ignored when scoring fact support.
_STOP = {
    "the",
    "a",
    "an",
    "of",
    "to",
    "in",
    "for",
    "and",
    "or",
    "be",
    "is",
    "are",
    "must",
    "not",
    "no",
    "any",
    "each",
    "that",
    "this",
    "with",
    "at",
    "on",
    "by",
    "as",
    "it",
    "its",
    "than",
    "from",
    "may",
    "which",
    "under",
    "when",
}


def _tokens(text: str) -> set[str]:
    return {w for w in re.findall(r"[a-z0-9.]+", text.lower()) if w not in _STOP and len(w) > 1}


def _clause_id(clause: str) -> str:
    return clause.rsplit("§", 1)[-1].strip()


def _load_cases(suite: str) -> list[dict[str, object]]:
    path = _SUITES_DIR / f"{suite}.jsonl"
    cases: list[dict[str, object]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if not s or s.startswith("##"):
            continue
        cases.append(json.loads(s))
    return cases


def _clause_text(conn: psycopg.Connection, slug: str, clause: str) -> tuple[bool, str]:
    """The ingested text of a clause AND its sub-paragraphs (a clause's meaning
    lives in its paragraphs, e.g. 25.1309(b) carries what 25.1309 'says')."""
    cid = _clause_id(clause)
    row = conn.execute(
        """SELECT count(*) FROM sections s JOIN documents d ON d.id = s.document_id
            WHERE d.slug = %s AND (s.clause_id = %s OR s.clause_id LIKE %s)""",
        (slug, cid, f"{cid}(%"),
    ).fetchone()
    exists = bool(row and row[0])

    rows = conn.execute(
        """SELECT c.content FROM chunks c JOIN documents d ON d.id = c.document_id
            WHERE d.slug = %s
              AND (split_part(c.clause_path, '§', 2) = %s
                   OR split_part(c.clause_path, '§', 2) LIKE %s)""",
        (slug, cid, f"{cid}(%"),
    ).fetchall()
    return exists, " ".join(r[0] for r in rows)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--slug", default="far-25")
    ap.add_argument(
        "--dsn",
        default="postgresql://groundcite:groundcite@localhost:5433/groundcite",
    )
    ap.add_argument("--suites", nargs="*", default=["core", "german", "negative"])
    args = ap.parse_args()

    lines: list[str] = [
        "# Golden-set verification worksheet",
        "",
        f"Corpus: `{args.slug}` (as ingested in Postgres). Generated by "
        "`scripts/verify_golden_set.py`.",
        "",
        "Spec §8 / prep task P2 require every expected clause to be **human-verified**.",
        "This worksheet does the mechanical half; **you** sign off on the flagged rows.",
        "It does not, and must not, edit `evals/suites/` (CLAUDE.md rule 13).",
        "",
        "- **MISSING** — the expected clause is not in the ingested corpus at all. "
        "The case can never pass; either the clause id is wrong or the corpus is short.",
        "- **WEAK** — the clause exists, but its ingested text shares little vocabulary "
        "with the case's `expected_facts`. Usually means the fact lives in a *different* "
        "clause. Worth a human read.",
        "- **OK** — clause exists and its text supports the expected facts. No action.",
        "",
    ]
    total = flagged = 0

    with psycopg.connect(args.dsn) as conn:
        for suite in args.suites:
            cases = _load_cases(suite)
            rows: list[str] = []
            for case in cases:
                if case.get("must_abstain"):
                    continue  # no expected clause by design — nothing to verify
                expected = list(case.get("expected_clauses", []))
                facts = list(case.get("expected_facts", []))
                question = str(case.get("question", ""))
                for clause in expected:
                    total += 1
                    exists, text = _clause_text(conn, args.slug, clause)
                    fact_toks = _tokens(" ".join(facts))
                    text_toks = _tokens(text)
                    overlap = len(fact_toks & text_toks) / len(fact_toks) if fact_toks else 1.0
                    if not exists:
                        verdict, note = "**MISSING**", "clause not ingested"
                    elif fact_toks and overlap < 0.5:
                        verdict, note = "**WEAK**", f"fact overlap {overlap:.0%}"
                    else:
                        verdict, note = "OK", f"fact overlap {overlap:.0%}"
                    if verdict != "OK":
                        flagged += 1
                        rows.append(f"| {verdict} | `{clause}` | {note} | {question[:78]} |")
            lines += [
                f"## Suite `{suite}` — {len(cases)} cases, {len(rows)} flagged",
                "",
            ]
            if rows:
                lines += [
                    "| verdict | expected clause | signal | question |",
                    "|---|---|---|---|",
                    *rows,
                    "",
                ]
            else:
                lines += ["No flags — every expected clause exists and is supported.", ""]

    lines += [
        "---",
        "",
        f"**{flagged} of {total} expected clauses flagged for human review.**",
        "",
        "Reviewing a flag: read the clause's ingested text, decide whether the case's "
        "expected clause is right. Then edit `evals/suites/*.jsonl` **yourself** and "
        "drop the `## DRAFT` / `VERIFY:` markers once the suite is frozen.",
    ]

    _OUT.parent.mkdir(parents=True, exist_ok=True)
    _OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{flagged}/{total} expected clauses flagged")
    print(f"worksheet: {_OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
